#!/usr/bin/env node
/**
 * Pull every region in one run.
 *
 *   TOURAPI_SERVICE_KEY=... TOURAPI_LANGS=ko,en,ja,zh-Hans,zh-Hant \
 *   node scripts/ingest-all.mjs
 *
 *   # or a subset
 *   node scripts/ingest-all.mjs --only busan,gyeongbuk,jeju
 *
 * Korea is 17 areaCodes. Counts below are the English catalogue as measured on
 * 2026-08-17 — the ceiling for multilingual rows, since English is the base we
 * join the other languages onto.
 *
 * Quota: the development account allows 1,000 calls per 상세기능 per day. This
 * run costs (pages × languages) per region — roughly 120 calls for the whole
 * country at 5 languages. Well inside the budget, and it only needs repeating
 * when the source data changes.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";

/** areaCode → our city id, display name, and the English record count. */
export const REGIONS = [
  { area: 1,  id: "seoul",     ko: "서울",   en: 716 },
  { area: 6,  id: "busan",     ko: "부산",   en: 163 },
  { area: 35, id: "gyeongbuk", ko: "경상북도", en: 269, note: "경주 포함" },
  { area: 36, id: "gyeongnam", ko: "경상남도", en: 171 },
  { area: 4,  id: "daegu",     ko: "대구",   en: 86 },
  { area: 5,  id: "gwangju",   ko: "광주",   en: 79 },
  { area: 3,  id: "daejeon",   ko: "대전",   en: 59 },
  { area: 37, id: "jeonbuk",   ko: "전북특별자치도", en: 117, note: "전주 포함" },
  { area: 38, id: "jeonnam",   ko: "전라남도", en: 215 },
  { area: 39, id: "jeju",      ko: "제주특별자치도", en: 176 },
  { area: 32, id: "gangwon",   ko: "강원특별자치도", en: 354 },
  { area: 31, id: "gyeonggi",  ko: "경기도", en: 342 },
  { area: 2,  id: "incheon",   ko: "인천",   en: 154 },
  { area: 34, id: "chungnam",  ko: "충청남도", en: 155 },
  { area: 33, id: "chungbuk",  ko: "충청북도", en: 90 },
  { area: 7,  id: "ulsan",     ko: "울산",   en: 44 },
  { area: 8,  id: "sejong",    ko: "세종특별자치시", en: 18 },
];

/**
 * 동해안 · 서해안 are NOT areaCodes — they cut across provinces:
 *
 *   동해안  강원 + 경북 + 울산 + 부산
 *   서해안  인천 + 경기 + 충남 + 전북 + 전남
 *
 * TourAPI has no "coast" dimension, so these have to be derived after ingest
 * by filtering on distance to the coastline, or by sigungu code. Do not fake
 * them with a region list — a traveler who picks 동해안 and gets an inland
 * temple has been lied to. Left unimplemented on purpose.
 */
export const COASTS = {
  east: { ko: "동해안", regions: ["gangwon", "gyeongbuk", "ulsan", "busan"], status: "not implemented" },
  west: { ko: "서해안", regions: ["incheon", "gyeonggi", "chungnam", "jeonbuk", "jeonnam"], status: "not implemented" },
};

const only = (process.argv.find((a) => a.startsWith("--only="))?.split("=")[1] ??
  (process.argv.includes("--only") ? process.argv[process.argv.indexOf("--only") + 1] : ""))
  .split(",").map((s) => s.trim()).filter(Boolean);

const targets = only.length ? REGIONS.filter((r) => only.includes(r.id)) : REGIONS;

if (!process.env.TOURAPI_SERVICE_KEY) {
  console.error("\n  TOURAPI_SERVICE_KEY is not set.\n");
  process.exit(1);
}

console.log(`\n  Ingesting ${targets.length} region(s) — about ${targets.reduce((n, r) => n + r.en, 0)} English records upstream\n`);

let ok = 0, failed = [];
for (const r of targets) {
  process.stdout.write(`  ${r.ko.padEnd(12)} area ${String(r.area).padStart(2)} … `);
  try {
    execFileSync(process.execPath, [
      "scripts/tourapi-ingest.mjs",
      "--area", String(r.area),
      "--city", r.id,
      "--name", r.ko,
      "--rows", String(Math.max(200, r.en + 100)),
    ], { stdio: ["ignore", "pipe", "pipe"] });
    execFileSync(process.execPath, ["scripts/romanize.mjs", `app/data/places/${r.id}.generated.ts`],
      { stdio: ["ignore", "pipe", "pipe"] });
    if (!process.argv.includes("--skip-hours")) {
      // detailIntro2 is one call per place — the slow part, but it is what turns
      // 확인 필요 into 공식. --skip-hours when you only want names and coordinates.
      execFileSync(process.execPath, ["scripts/enrich-hours.mjs", `app/data/places/${r.id}.generated.ts`],
        { stdio: ["ignore", "pipe", "pipe"] });
    }
    console.log("done");
    ok++;
  } catch (e) {
    console.log("FAILED");
    failed.push(r.id);
  }
}

/**
 * Write the registry.
 *
 * Without this step, ingesting 3,000 places changes nothing the user can see —
 * the app only knows the cities listed in a registry. Generating it here means
 * "run the ingest" is one action, not two, and the registry can never drift
 * from the files on disk.
 */
const written = targets.filter((r) => !failed.includes(r.id) &&
  fs.existsSync(`app/data/places/${r.id}.generated.ts`));

fs.writeFileSync("app/data/places/generated.ts",
`// AUTO-GENERATED by scripts/ingest-all.mjs — do not edit by hand.
// Source: 한국관광공사 TourAPI. Every row is coverage "seeded": names,
// coordinates and addresses are official; hours and fees are still 확인 필요.
${written.map((r) => `import { ${r.id}Options } from "./${r.id}.generated";`).join("\n")}
import type { JourneyOption } from "../../lib/types";

export const GENERATED_CITIES: { id: string; ko: string; en: string; options: JourneyOption[] }[] = [
${written.map((r) => `  { id: "${r.id}", ko: "${r.ko}", en: "${r.id}", options: ${r.id}Options },`).join("\n")}
];
`);

console.log(`
  ${ok} region(s) written to app/data/places/*.generated.ts${failed.length ? `\n  failed: ${failed.join(", ")}` : ""}
  registry written: app/data/places/generated.ts  (${written.length} cities)

  Next:
    1. Review the romanizations marked /* rule-based — review */.
    2. Hours came from detailIntro2 where the source published them; the rest
       stay 확인 필요 on purpose. Re-run to refresh the date stamp.

  동해안 / 서해안 are not areaCodes and are deliberately not faked here.
  See COASTS in this file.
`);
