/**
 * 정책·안내 페이지 본문 — 한 곳에서 3개 언어로 관리한다.
 *
 * 2026-08-16. 「일본사람한테는 일본어로 글이 뜨고 들어가면 껍데기까지 일본어로 보여야지」
 * 라는 지시의 **마지막 남은 구멍**이었다. 기사와 메뉴는 3개 언어가 됐는데,
 * 푸터의 정책 링크만 영어로 튕겨 나갔다. 「（英語）」라고 적어 두긴 했지만,
 * 개인정보 처리방침과 제휴 고지는 「나중에 읽으세요」로 넘길 수 있는 종류가 아니다.
 * 그건 **읽는 사람의 권리에 관한 문서**다.
 *
 * 왜 페이지 안에 두지 않는가.
 *   영어 문장을 .astro 에 두고 번역만 따로 두면, 영어를 고칠 때 번역이 남는다.
 *   오늘 하루에 여섯 번 반복한 모양이다. 그래서 영어도 여기 둔다.
 *
 * 구조는 블록 배열이다. { h2 } 는 소제목, { p } 는 문단, { ul } 은 목록,
 * { raw } 는 링크가 들어가야 해서 컴포넌트가 직접 그리는 자리다.
 *
 * 번역 상태: ja·zh-hans 는 AI 번역이고 원어민 교정을 받지 않았다.
 * 법률 문서로서의 구속력은 영어판을 기준으로 한다 — 각 페이지 하단에 그렇게 적는다.
 */

/** 각 언어에서 「이 번역은 참고용, 원문은 영어판」이라고 적는 줄. */
export const POLICY_NOTE = {
  en: null,
  ja: 'この日本語版はAIによる翻訳です。読みやすさのために用意していますが、'
    + '法的な基準となるのは英語版です。相違がある場合は英語版が優先します。',
  'zh-hans': '本中文版为 AI 翻译，仅供阅读方便。具有法律效力的版本为英文版；'
    + '如有出入，以英文版为准。',
  'zh-hant': '本中文版為 AI 翻譯，僅供閱讀方便。具法律效力的版本為英文版；'
    + '如有出入，以英文版為準。',
};

export const POLICY = {
  /* ─────────────────────────────── About ─────────────────────────────── */
  about: {
    en: {
      title: 'About',
      description: 'What HANKUKIN is, who makes it, and how it is researched and written.',
      h1: 'About HANKUKIN',
      updated: 'Last updated 13 August 2026',
      blocks: [
        { p: 'HANKUKIN is an independent guide for people who found Korea through a drama, a film, a music video or a song, and want to know what is actually there. We start from the story — a scene, a place, a phrase — and follow it through to the practical end: how to get there, what it costs, what the words meant, and what you can buy from home if you cannot travel.' },
        { h2: 'What we publish' },
        { ul: [
          ['Scenes', 'filming locations and the places around them, with routes, costs and photo guidance.'],
          ['Now', 'what is currently gaining attention in Korea, based on public data rather than guesswork.'],
          ['Decode', 'Korean expressions and the tone, politeness and humour that subtitles cannot carry.'],
          ['Culture & History', 'the longer background behind the places and stories.'],
        ] },
        { h2: 'How this site is made' },
        { raw: 'madeWith' },
        { p: 'We think you should be told this plainly rather than discover it. Every article carries its sources and the date it was last verified. If something is wrong, we would rather take the page down and re-check it than leave it up.' },
        { h2: 'What we will not do' },
        { p: 'We do not publish where artists live, who they are seeing, where they were spotted, or which restaurant they supposedly frequent. We do not reproduce drama stills or celebrity photographs whose rights are unclear. We do not claim an artist uses a product unless there is an official source saying so. These are not editorial preferences — they are rules the publishing system enforces.' },
        { h2: 'Independence' },
        { raw: 'independence' },
        { h2: 'Contact' },
        { raw: 'contact' },
      ],
      madeWithA: 'HANKUKIN is run by one person. Research, drafting, translation, link checking and fact verification are carried out with AI assistance under a written ',
      madeWithLink: 'editorial policy',
      madeWithB: '. That policy decides what may be stated as fact, what must be softened, and what is discarded outright — and it is applied by the system before anything is published, not afterwards.',
      independenceA: 'HANKUKIN is not affiliated with any broadcaster, production company, agency, artist, tourism authority or local government. Where we earn commission, we say so on the page. See our ',
      independenceLink: 'affiliate disclosure',
      independenceB: '.',
      contactA: ' — or use the ',
      contactLink: 'contact page',
      contactB: '.',
    },
    ja: {
      title: 'このサイトについて',
      description: 'HANKUKINとは何か、誰が作っているのか、どう調べて書いているのか。',
      h1: 'HANKUKINについて',
      updated: '最終更新 2026年8月13日',
      blocks: [
        { p: 'HANKUKINは、ドラマや映画、ミュージックビデオや曲をきっかけに韓国を知り、「実際にそこには何があるのか」を知りたい人のための独立系ガイドです。物語——ある場面、ある場所、あるひとこと——から出発して、実際的な終点まで追いかけます。どう行くのか、いくらかかるのか、その言葉は何を意味していたのか、そして旅に出られないなら家から何が買えるのか。' },
        { h2: '扱うもの' },
        { ul: [
          ['Scenes', 'ロケ地と、その周辺。行き方、費用、撮影の際の注意まで。'],
          ['Now', 'いま韓国で注目されているもの。憶測ではなく公開データに基づいて。'],
          ['Decode', '字幕が運びきれない韓国語の言い回し——語調、敬意、笑いのつぼ。'],
          ['Culture & History', '場所と物語の背後にある、もっと長い時間の話。'],
        ] },
        { h2: 'どう作られているか' },
        { raw: 'madeWith' },
        { p: 'これは、あとから気づかれるより先に、はっきりお伝えすべきことだと考えています。すべての記事に出典と最終確認日を載せています。間違いが見つかったときは、訂正を添えたまま残すのではなく、ページを取り下げて確認し直します。' },
        { h2: 'やらないこと' },
        { p: 'アーティストの住所、交際相手、目撃情報、行きつけとされる店——書きません。権利関係が不明なドラマの場面写真や芸能人の写真も使いません。公式の出典がない限り「このアーティストがこの製品を使っている」とも書きません。これは編集方針の好みではなく、公開システムが強制しているルールです。' },
        { h2: '独立性' },
        { raw: 'independence' },
        { h2: 'お問い合わせ' },
        { raw: 'contact' },
      ],
      madeWithA: 'HANKUKINは一人で運営しています。調査、執筆、翻訳、リンク確認、事実確認は、文書化された',
      madeWithLink: '編集方針',
      madeWithB: 'のもとでAIの支援を受けて行っています。この方針が、事実として書いてよいこと、和らげるべきこと、そもそも捨てるべきことを決めます。しかもそれは公開のあとではなく、公開の前にシステムが適用します。',
      independenceA: 'HANKUKINは、放送局・制作会社・事務所・アーティスト・観光当局・自治体のいずれとも提携していません。手数料を得ている場合は、そのページに明記します。',
      independenceLink: 'アフィリエイトに関する開示',
      independenceB: 'をご覧ください。',
      contactA: '　または',
      contactLink: 'お問い合わせページ',
      contactB: 'から。',
    },
    'zh-hans': {
      title: '关于本站',
      description: 'HANKUKIN 是什么、由谁制作、如何查证与写作。',
      h1: '关于 HANKUKIN',
      updated: '最后更新 2026年8月13日',
      blocks: [
        { p: 'HANKUKIN 是一份独立指南，写给那些因为一部剧、一部电影、一支 MV 或一首歌而认识韩国，并且想知道"那里实际上是什么样"的人。我们从故事出发——一个场景、一个地方、一句话——一直追到实际的终点：怎么去、多少钱、那句话原本是什么意思，以及如果去不了，在家里能买到什么。' },
        { h2: '我们写什么' },
        { ul: [
          ['Scenes', '取景地和它周边的地方，包括路线、花费和拍照注意事项。'],
          ['Now', '韩国当下正在被关注的事，依据公开数据而非猜测。'],
          ['Decode', '字幕承载不了的韩语——语气、敬意、笑点。'],
          ['Culture & History', '这些地方与故事背后更长的来龙去脉。'],
        ] },
        { h2: '这个网站是怎么做出来的' },
        { raw: 'madeWith' },
        { p: '我们认为这件事应该直接告诉你，而不是让你自己发现。每篇文章都附有出处和最后核实日期。如果哪里错了，我们宁可把页面撤下来重新核对，也不愿挂着一条更正说明继续放着。' },
        { h2: '我们不做的事' },
        { p: '我们不写艺人住在哪里、和谁交往、在哪里被拍到、据说常去哪家餐厅。我们不使用权利关系不明的剧照或艺人照片。除非有官方出处，我们不会说某位艺人在用某个产品。这些不是编辑偏好，而是发布系统强制执行的规则。' },
        { h2: '独立性' },
        { raw: 'independence' },
        { h2: '联系我们' },
        { raw: 'contact' },
      ],
      madeWithA: 'HANKUKIN 由一个人运营。资料查证、写作、翻译、链接检查和事实核对，都是在一份成文的',
      madeWithLink: '编辑方针',
      madeWithB: '之下借助 AI 完成的。这份方针决定什么可以作为事实写出来、什么必须放软、什么直接舍弃——而且它是在发布之前由系统执行的，不是事后补的。',
      independenceA: 'HANKUKIN 与任何电视台、制作公司、经纪公司、艺人、旅游机构或地方政府都没有从属关系。凡是我们能拿到佣金的地方，都会在该页面写明。请参见我们的',
      independenceLink: '联盟营销披露',
      independenceB: '。',
      contactA: '　或使用',
      contactLink: '联系页面',
      contactB: '。',
    },
  },

  /* ────────────────────────────── Contact ────────────────────────────── */
  contact: {
    en: {
      title: 'Contact & Report an Error',
      description: 'Tell us about an out-of-date price, a closed venue, a wrong location or a translation that misses the point.',
      h1: 'Contact & Report an Error',
      updated: 'Last updated 13 August 2026',
      lead: ['Email ', '. We read everything, though we cannot promise an individual reply to every message.'],
      blocks: [
        { h2: 'Reporting something wrong' },
        { p: 'This is the most useful thing you can send us. Please include the page address and what you found — a venue that has closed, a price that has changed, a route that no longer runs, a location that is wrong, or a translation that misses the meaning.' },
        { p: 'Where reports point to a substantive error, we withdraw the page from public view while we re-check it rather than leaving it up with a correction note.' },
        { h2: 'Partnerships' },
        { p: 'If you run a venue, tour, studio or shop and want to work with us, write to the same address with what you do and where you are. We will tell you honestly whether our readers are a fit.' },
        { h2: 'Rights holders' },
        { p: 'If you believe material on this site infringes your rights, contact us with the page address and a description of the material. We remove first and discuss afterwards.' },
      ],
    },
    ja: {
      title: 'お問い合わせ・誤りのご指摘',
      description: '古くなった料金、閉店した店、間違った場所、意味を取り違えた翻訳——お知らせください。',
      h1: 'お問い合わせ・誤りのご指摘',
      updated: '最終更新 2026年8月13日',
      lead: ['メールは', 'まで。すべて読んでいますが、一通ずつの返信はお約束できません。'],
      blocks: [
        { h2: '間違いを教えてください' },
        { p: 'これがいちばんありがたいご連絡です。ページのアドレスと、お気づきの内容をお書きください——閉店した店、変わった料金、なくなった路線、違う場所、意味がずれている翻訳。' },
        { p: '内容に関わる誤りのご指摘があった場合、訂正を添えて残すのではなく、確認し直すあいだページを公開から下げます。' },
        { h2: '提携について' },
        { p: '店舗・ツアー・スタジオ・ショップを運営されていて一緒に何かをしたい場合は、同じアドレスに、何をされていてどこにあるのかをお書きください。読者層が合うかどうか、正直にお伝えします。' },
        { h2: '権利者の方へ' },
        { p: '当サイトの掲載物が権利を侵害しているとお考えの場合は、ページのアドレスと該当箇所をお知らせください。まず削除し、お話はそのあとで伺います。' },
      ],
    },
    'zh-hans': {
      title: '联系我们・报告错误',
      description: '过时的价格、已关闭的场所、错误的地点，或是没抓住原意的翻译——请告诉我们。',
      h1: '联系我们・报告错误',
      updated: '最后更新 2026年8月13日',
      lead: ['请发邮件至 ', '。我们每封都会读，但无法承诺逐一回复。'],
      blocks: [
        { h2: '请告诉我们哪里错了' },
        { p: '这是你能给我们的最有用的东西。请附上页面地址和你发现的问题——已经关门的店、变了的价格、不再运行的路线、错误的位置，或是没译准意思的句子。' },
        { p: '如果指出的是实质性错误，我们会在重新核对期间把页面撤下，而不是挂着一条更正说明继续放着。' },
        { h2: '合作' },
        { p: '如果你经营场馆、旅行团、工作室或店铺并希望合作，请写信到同一地址，说明你做什么、在哪里。我们会诚实地告诉你我们的读者是否合适。' },
        { h2: '权利人' },
        { p: '如果你认为本站内容侵犯了你的权利，请附页面地址和具体内容与我们联系。我们先删除，再讨论。' },
      ],
    },
  },
};

/* ─────────────────── Affiliate disclosure / Privacy ─────────────────── */
/*
 * 이 둘은 나중으로 미룰 수 있는 종류가 아니다.
 * 제휴 고지는 **돈을 받는다는 사실**의 고지이고,
 * 개인정보 처리방침은 **쿠키를 심는다는 사실**의 고지다.
 * 읽는 사람이 못 읽는 언어로 적혀 있으면 고지한 것이 아니다.
 */
POLICY['affiliate-disclosure'] = {
  en: {
    title: 'Affiliate Disclosure',
    description: 'How HANKUKIN earns money, and what that does and does not change about what we publish.',
    h1: 'Affiliate Disclosure',
    updatedPrefix: 'Last updated ',
    liveHeading: 'Who we currently earn from',
    noneA: 'Nobody.', noneB: ' We have no approved affiliate programme at present and earn nothing from any link on this site.',
    approved: 'approved',
    generated: 'This list is generated from our own merchant registry rather than typed by hand, so it cannot fall out of date. If a programme is added or ends, this page changes with it — as does the notice in the site footer.',
    leadA: 'HANKUKIN earns commission on some bookings and purchases made through links on this site. If you book a hotel, buy a tour ticket or order a product through one of those links, the merchant may pay us a percentage of the sale. ',
    leadStrong: 'You pay the same price either way.',
    blocks: [
      { h2: 'How to tell' },
      { p: "Every article containing commission links carries a notice near the top. Links to merchants are marked as sponsored links in the page's HTML, which is how search engines are told about them as well." },
      { h2: 'What the money does not buy' },
      { p: 'Merchants do not choose which places we write about, do not review articles before publication, and cannot pay to be described as somewhere an artist visited. Whether a place is a confirmed filming location is decided by its sources, and that decision is made before any commercial link is attached.' },
      { p: 'Our trend reporting and our product recommendations are produced by separate processes on purpose. We do not decide that something is trending because we can sell it.' },
      { h2: 'Sponsored content' },
      { p: 'If we ever publish content paid for by a partner, it will be labelled Sponsored at the top of the page, in the language you are reading. We have no sponsored content at present.' },
      { h2: 'Advertising' },
      { raw: 'ads' },
      { h2: 'Prices and availability' },
      { p: "Prices, availability and shipping destinations change without notice, and vary by country. Where we quote a figure, we show the date it was checked. Always confirm the current price on the merchant's own page before booking or buying." },
      { h2: 'Questions' },
      { raw: 'email' },
    ],
    adsA: 'We may display advertising from third-party networks. Advertising is separate from our affiliate links and is not chosen by us article by article. See our ',
    adsLink: 'privacy policy',
    adsB: ' for how advertising cookies work.',
  },
  ja: {
    title: 'アフィリエイトに関する開示',
    description: 'HANKUKINがどうやって収入を得ているか。そしてそれが、書く内容を変えるのか変えないのか。',
    h1: 'アフィリエイトに関する開示',
    updatedPrefix: '最終更新 ',
    liveHeading: '現在、収入を得ている相手',
    noneA: 'ありません。', noneB: '現在、承認されたアフィリエイトプログラムはなく、当サイトのどのリンクからも収入を得ていません。',
    approved: '承認日',
    generated: 'この一覧は手入力ではなく、当サイトの提携先登録簿から自動生成しています。だから古くなりません。プログラムが増えたり終わったりすれば、このページもフッターの表示も一緒に変わります。',
    leadA: 'HANKUKINは、当サイトのリンク経由で行われた一部の予約や購入について手数料を受け取ります。リンク経由でホテルを予約したり、ツアーのチケットや商品を購入したりすると、販売者が売上の一部を当サイトに支払うことがあります。',
    leadStrong: 'どちらの経路でも、お支払いになる金額は同じです。',
    blocks: [
      { h2: '見分け方' },
      { p: '手数料リンクを含む記事には、上部に必ずその旨を表示しています。販売者へのリンクはページのHTML上でスポンサードリンクとして印を付けており、検索エンジンにもそう伝わります。' },
      { h2: 'お金で買えないもの' },
      { p: '販売者は、当サイトがどの場所を取り上げるかを決められません。公開前に記事を確認することもできません。「あるアーティストが訪れた場所」と書かせるために支払うこともできません。ロケ地として確認済みかどうかは出典が決めることであり、その判断は商業リンクを付ける前に済んでいます。' },
      { p: 'トレンドの報告と商品の紹介は、意図的に別々の工程で作っています。売れるからトレンドだ、とは判断しません。' },
      { h2: 'スポンサード記事' },
      { p: 'もし提携先の費用負担で記事を出すことがあれば、ページ上部に、お読みになっている言語で「スポンサード」と表示します。現在、そうした記事はありません。' },
      { h2: '広告' },
      { raw: 'ads' },
      { h2: '料金と在庫' },
      { p: '料金、在庫、配送先は予告なく変わり、国によっても異なります。数字を挙げる場合は、確認した日付を併記しています。予約・購入の前に、必ず販売者自身のページで現在の価格をご確認ください。' },
      { h2: 'お問い合わせ' },
      { raw: 'email' },
    ],
    adsA: '第三者の広告ネットワークによる広告を表示することがあります。広告はアフィリエイトリンクとは別のもので、記事ごとに当サイトが選んでいるわけではありません。広告用クッキーの仕組みについては',
    adsLink: 'プライバシーポリシー',
    adsB: 'をご覧ください。',
  },
  'zh-hans': {
    title: '联盟营销披露',
    description: 'HANKUKIN 靠什么赚钱，以及这件事会不会改变我们写的内容。',
    h1: '联盟营销披露',
    updatedPrefix: '最后更新 ',
    liveHeading: '目前我们从谁那里获得收入',
    noneA: '没有。', noneB: '目前我们没有已获批准的联盟营销项目，本站任何链接都不会带来收入。',
    approved: '批准日期',
    generated: '这份名单不是手写的，而是从我们自己的商家登记表自动生成的，因此不会过时。项目新增或结束时，本页和页脚的提示会一起改变。',
    leadA: '通过本站链接完成的部分预订和购买，HANKUKIN 会获得佣金。如果你通过这些链接订酒店、买行程票或下单商品，商家可能会把销售额的一定比例支付给我们。',
    leadStrong: '无论走哪条路径，你付的价格都一样。',
    blocks: [
      { h2: '怎么分辨' },
      { p: '凡是含有佣金链接的文章，顶部都有提示。指向商家的链接在页面 HTML 中被标记为赞助链接，搜索引擎也是这样被告知的。' },
      { h2: '这些钱买不到什么' },
      { p: '商家不能决定我们写哪些地方，不能在发布前审阅文章，也不能出钱让某处被描述成"某位艺人去过的地方"。一个地方是否是确认的取景地，由它的出处决定，而这个判断在任何商业链接被挂上之前就已经做完了。' },
      { p: '我们的趋势报道和商品推荐是有意分开的两套流程。我们不会因为某样东西能卖，就判定它在流行。' },
      { h2: '赞助内容' },
      { p: '如果我们发布由合作方付费的内容，会在页面顶部用你正在阅读的语言标注"赞助"。目前没有此类内容。' },
      { h2: '广告' },
      { raw: 'ads' },
      { h2: '价格与供应' },
      { p: '价格、供应情况和配送地区会不经通知就变化，并且因国家而异。凡是我们给出数字的地方，都会标明核实日期。预订或购买前，请务必在商家自己的页面上确认当前价格。' },
      { h2: '有疑问' },
      { raw: 'email' },
    ],
    adsA: '我们可能展示第三方广告网络的广告。广告与我们的联盟链接是两回事，并非由我们逐篇挑选。关于广告 Cookie 的运作方式，请参见我们的',
    adsLink: '隐私政策',
    adsB: '。',
  },
};

POLICY.privacy = {
  en: {
    title: 'Privacy Policy',
    description: 'What data HANKUKIN collects, which third parties are involved, and how cookies are used.',
    h1: 'Privacy Policy',
    updated: 'Last updated 13 August 2026',
    leadA: 'This policy explains what happens to data when you visit ',
    leadB: '. It covers cookies, analytics, advertising and affiliate tracking.',
    blocks: [
      { h2: 'What we collect ourselves' },
      { p: 'We do not ask you to create an account and we do not collect names, addresses or payment details. If you email us or submit an error report, we receive whatever you choose to send and keep it only as long as needed to respond.' },
      { h2: 'Cookies, web beacons and IP addresses' },
      { p: 'This site and the third parties listed below may use cookies, web beacons and similar technologies, and may receive your IP address, device and browser information, approximate location derived from your IP address, and the pages you view. This information is used to measure traffic, to attribute referrals to merchants, and to select and measure advertising.' },
      { h2: 'Third parties that may set cookies' },
      { raw: 'thirdParties' },
      { h2: 'Controlling cookies' },
      { p: 'Most browsers let you refuse or delete cookies through their settings. Blocking cookies will not prevent you from reading this site, though some measurement and attribution will not work.' },
      { h2: 'Children' },
      { raw: 'children' },
      { h2: 'Your rights' },
      { raw: 'rights' },
      { h2: 'External links' },
      { p: 'This site links to merchants, official pages and news sources. We are not responsible for the privacy practices of those sites.' },
      { h2: 'Changes' },
      { p: 'We will update this page when our processing changes, and will revise the date at the top.' },
      { h2: 'Contact' },
      { raw: 'email' },
    ],
    tpLead: 'Please note that third parties, including advertising partners, may set cookies on your device through this site.',
    tpLeadB: ' We do not control those cookies. The third parties we work with are:',
    tpAnalytics: ['Analytics providers', 'to count visits and understand which pages are useful.'],
    tpAdsName: 'Advertising networks, including Google',
    tpAdsA: 'Google and its partners may use cookies to serve ads based on your prior visits to this and other websites. You can review how Google uses information from sites that use its services at ',
    tpAdsB: ', and manage personalised advertising at ',
    tpAdsC: '. You may opt out of personalised advertising from participating vendors at ',
    tpAdsD: '.',
    tpAffiliate: ['Affiliate networks and merchants', 'when you follow a link to a merchant, that merchant may set a cookie to attribute your visit to us. Their own privacy policy governs what happens on their site.'],
    childrenA: 'This site is not directed at children, and we do not knowingly collect personal information from them. We also do not collect or republish personal information about minors as editorial subject matter — see our ',
    childrenLink: 'editorial policy',
    childrenB: '.',
    rightsA: 'Depending on where you live, you may have the right to access, correct or delete personal data we hold about you, or to object to its processing. Contact us at ',
    rightsB: ' and we will respond within a reasonable period.',
  },
  ja: {
    title: 'プライバシーポリシー',
    description: 'HANKUKINが取得するデータ、関わる第三者、クッキーの使われ方について。',
    h1: 'プライバシーポリシー',
    updated: '最終更新 2026年8月13日',
    leadA: 'このポリシーは、',
    leadB: 'をご覧になったときにデータがどう扱われるかを説明するものです。クッキー、アクセス解析、広告、アフィリエイトの計測を対象とします。',
    blocks: [
      { h2: '当サイト自身が取得するもの' },
      { p: 'アカウント登録はお願いしておらず、氏名・住所・決済情報を取得することもありません。メールや誤りのご指摘をいただいた場合は、お送りいただいた内容をお預かりし、返信に必要な期間だけ保管します。' },
      { h2: 'クッキー、ウェブビーコン、IPアドレス' },
      { p: '当サイトおよび下記の第三者は、クッキー、ウェブビーコンおよび類似の技術を使用することがあり、お客様のIPアドレス、端末およびブラウザの情報、IPアドレスから推定されるおおよその所在地、閲覧したページを受け取ることがあります。これらはアクセス数の計測、販売者への送客の紐づけ、広告の選択と効果測定に使われます。' },
      { h2: 'クッキーを設定しうる第三者' },
      { raw: 'thirdParties' },
      { h2: 'クッキーの制御' },
      { p: 'ほとんどのブラウザでは、設定からクッキーを拒否または削除できます。クッキーを止めても当サイトの記事は読めますが、一部の計測と送客の紐づけは働かなくなります。' },
      { h2: '子どもについて' },
      { raw: 'children' },
      { h2: 'お客様の権利' },
      { raw: 'rights' },
      { h2: '外部リンク' },
      { p: '当サイトは販売者、公式ページ、報道記事へリンクしています。リンク先のプライバシーの取り扱いについて、当サイトは責任を負いません。' },
      { h2: '変更' },
      { p: '取り扱いが変わった場合はこのページを更新し、冒頭の日付を改めます。' },
      { h2: 'お問い合わせ' },
      { raw: 'email' },
    ],
    tpLead: '広告パートナーを含む第三者が、当サイトを通じてお客様の端末にクッキーを設定する場合があります。',
    tpLeadB: 'それらのクッキーを当サイトは管理していません。関わりのある第三者は次のとおりです。',
    tpAnalytics: ['アクセス解析事業者', '訪問数を数え、どのページが役に立っているかを把握するため。'],
    tpAdsName: 'Googleを含む広告ネットワーク',
    tpAdsA: 'Googleおよびそのパートナーは、当サイトや他のサイトへの過去の訪問に基づいて広告を配信するためにクッキーを使用することがあります。Googleのサービスを利用するサイトから得た情報をGoogleがどう扱うかは',
    tpAdsB: 'でご確認いただけます。パーソナライズ広告の設定は',
    tpAdsC: 'で管理できます。参加事業者によるパーソナライズ広告の停止は',
    tpAdsD: 'から行えます。',
    tpAffiliate: ['アフィリエイトネットワークおよび販売者', '販売者へのリンクをたどると、その販売者が当サイト経由であることを記録するためにクッキーを設定することがあります。販売者のサイト上での取り扱いは、その販売者自身のプライバシーポリシーによります。'],
    childrenA: '当サイトは子ども向けではなく、子どもから個人情報を意図的に取得することはありません。また、未成年者の個人情報を記事の題材として集めたり再掲載したりもしません。',
    childrenLink: '編集方針',
    childrenB: 'をご覧ください。',
    rightsA: 'お住まいの地域によっては、当サイトが保持するお客様の個人データについて、開示・訂正・削除を求める権利、または処理に異議を述べる権利がある場合があります。',
    rightsB: 'までご連絡ください。合理的な期間内に対応します。',
  },
  'zh-hans': {
    title: '隐私政策',
    description: 'HANKUKIN 收集哪些数据、涉及哪些第三方、Cookie 如何使用。',
    h1: '隐私政策',
    updated: '最后更新 2026年8月13日',
    leadA: '本政策说明你访问 ',
    leadB: ' 时数据会如何被处理，涵盖 Cookie、访问分析、广告和联盟营销追踪。',
    blocks: [
      { h2: '我们自己收集什么' },
      { p: '我们不要求你注册账号，也不收集姓名、地址或支付信息。如果你给我们发邮件或提交错误报告，我们会收到你选择发送的内容，并只在回复所需的期间内保留。' },
      { h2: 'Cookie、网络信标和 IP 地址' },
      { p: '本站及下列第三方可能使用 Cookie、网络信标及类似技术，并可能获得你的 IP 地址、设备与浏览器信息、由 IP 推断的大致位置，以及你浏览过的页面。这些信息用于统计访问量、把送客归因给商家，以及选择和衡量广告。' },
      { h2: '可能设置 Cookie 的第三方' },
      { raw: 'thirdParties' },
      { h2: '如何控制 Cookie' },
      { p: '大多数浏览器允许你在设置中拒绝或删除 Cookie。阻止 Cookie 不会妨碍你阅读本站，但部分统计和归因将无法工作。' },
      { h2: '关于儿童' },
      { raw: 'children' },
      { h2: '你的权利' },
      { raw: 'rights' },
      { h2: '外部链接' },
      { p: '本站会链接到商家、官方页面和新闻来源。我们不对这些站点的隐私做法负责。' },
      { h2: '变更' },
      { p: '当我们的处理方式发生变化时，我们会更新本页并修改顶部的日期。' },
      { h2: '联系我们' },
      { raw: 'email' },
    ],
    tpLead: '请注意：包括广告合作方在内的第三方，可能通过本站在你的设备上设置 Cookie。',
    tpLeadB: '我们无法控制这些 Cookie。与我们有关的第三方包括：',
    tpAnalytics: ['访问分析服务商', '用于统计访问量、了解哪些页面有用。'],
    tpAdsName: '包括 Google 在内的广告网络',
    tpAdsA: 'Google 及其合作伙伴可能使用 Cookie，根据你此前对本站及其他网站的访问投放广告。关于 Google 如何使用来自其服务站点的信息，可在 ',
    tpAdsB: ' 查看；个性化广告可在 ',
    tpAdsC: ' 管理。你也可以在 ',
    tpAdsD: ' 退出参与厂商的个性化广告。',
    tpAffiliate: ['联盟网络与商家', '当你点击前往商家的链接时，该商家可能设置 Cookie，把这次访问归因给我们。在商家自己的网站上发生什么，由他们自己的隐私政策约束。'],
    childrenA: '本站不面向儿童，我们也不会有意收集儿童的个人信息。我们同样不会把未成年人的个人信息作为报道题材来收集或转载——请参见我们的',
    childrenLink: '编辑方针',
    childrenB: '。',
    rightsA: '视你所在地区而定，你可能有权访问、更正或删除我们持有的你的个人数据，或反对我们对其进行处理。请通过 ',
    rightsB: ' 与我们联系，我们会在合理期限内回复。',
  },
};

POLICY['editorial-policy'] = {
  en: {
    title: 'Editorial Policy',
    description: 'Which sources we accept, how claims are worded, and what we refuse to publish.',
    h1: 'Editorial Policy', updated: 'Last updated 13 August 2026',
    lead: 'This page describes how information on HANKUKIN is sourced, graded and worded. It is written for readers, but it is also the specification the publishing system runs on.',
    blocks: [
      { h2: 'Sources we accept' },
      { ol: ['Broadcasters, production companies and agencies', 'Official artist and cast channels', 'Korea Tourism Organization, local governments and cultural institutions', 'Official restaurant, hotel and brand websites', 'Map and booking platforms', 'Named aggregate data such as Naver DataLab', 'Official interviews and established news media'] },
      { h2: 'Sources we do not treat as fact' },
      { ol: ['Anonymous community posts', 'Fan blogs without their own sourcing', 'Sighting reports', 'Private accounts', 'Re-uploaded video whose only sourcing is its own description'] },
      { h2: 'How claims are worded' },
      { p: "The strength of a statement is determined by its sources, not by an editor's confidence. Every location claim on this site carries one of the following labels, and the label is assigned automatically:" },
      { ol: ['Official filming location — confirmed by the production or a public body', 'Confirmed in an official interview — a linked interview says so', 'Official social media appearance — posted by an official account', 'Reported by reliable media — at least two established outlets', 'Inspired by the scene/look — a resemblance, not a confirmed fact', 'Suggested nearby experience — our own recommendation, unrelated to any artist'] },
      { p: 'If the evidence for a stronger label is missing, the statement is automatically demoted to a weaker one. It is never promoted.' },
      { h2: 'What is discarded outright' },
      { p: 'The following are removed before drafting and are never escalated to a human for a decision: current or former home addresses; family, friends or schools; real-time movements or sightings; unverified claims about places an artist frequents; private relationships or health; medical or cosmetic-procedure claims attached to a named person; routes that could enable stalking; any personal information about a minor; and images whose rights are unclear.' },
      { h2: 'Photographs and images' },
      { p: 'We do not copy drama screencaps or celebrity photographs. Images on this site are either openly licensed location photography, self-made maps and diagrams, merchant-supplied product images, or clearly labelled illustrations. Every image stores its licence, source and credit — an image missing any of the three cannot be published.' },
      { h2: 'Photo guidance' },
      { p: 'Where we suggest how to frame a shot, we are describing a vantage point that visitors can reach. We are not stating where the production placed its camera, and we say so on every page that carries photo guidance.' },
      { h2: 'Keeping pages current' },
      { p: 'Addresses, business status and outbound links are checked automatically on a schedule. Prices carry the date they were checked. When a place closes permanently, booking and purchase links are removed and the page is kept only as a record of the filming site. Every article shows its last verification date.' },
      { h2: 'Corrections' },
      { p: 'Report an error from any page. Where reports indicate a substantive problem, the page is withdrawn from public view while it is re-checked, rather than left up with a note.' },
      { h2: 'AI assistance' },
      { p: 'Research, drafting, translation and verification are carried out with AI assistance under this policy. Sources are recorded and linked. AI assistance does not relax any rule on this page — the rules exist precisely because the volume is automated.' },
    ],
  },
  ja: {
    title: '編集方針',
    description: 'どの出典を採るか、主張をどう書くか、何を載せないか。',
    h1: '編集方針', updated: '最終更新 2026年8月13日',
    lead: 'このページは、HANKUKINの情報がどこから来て、どう格付けされ、どう書かれるかを説明するものです。読者に向けて書いていますが、同時に、公開システムが実際に従っている仕様書でもあります。',
    blocks: [
      { h2: '事実として採る出典' },
      { ol: ['放送局、制作会社、事務所', 'アーティストおよび出演者の公式チャンネル', '韓国観光公社、自治体、文化機関', '飲食店・ホテル・ブランドの公式サイト', '地図および予約プラットフォーム', 'ネイバーデータラボなど、出所の明示された集計データ', '公式インタビューおよび定評ある報道機関'] },
      { h2: '事実としては採らない出典' },
      { ol: ['匿名の掲示板投稿', '自前の出典を示さないファンブログ', '目撃情報', '非公開アカウント', '説明文以外に出典のない転載動画'] },
      { h2: '主張の書き分け' },
      { p: '文の強さは出典が決めます。編集者の確信度ではありません。当サイトのロケ地に関する記述には必ず次のいずれかのラベルが付き、そのラベルは自動で割り当てられます。' },
      { ol: ['公式ロケ地 — 制作側または公的機関が確認', '公式インタビューで確認 — リンク先のインタビューにそう書かれている', '公式SNSでの登場 — 公式アカウントが投稿', '信頼できる報道 — 定評ある媒体が2社以上', '場面・雰囲気からの連想 — 似ているだけで、確認された事実ではない', '近隣のおすすめ — 当サイト独自の推薦で、アーティストとは無関係'] },
      { p: 'より強いラベルの根拠が足りない場合、記述は自動的に弱いほうへ格下げされます。逆向きの繰り上げは起きません。' },
      { h2: '最初から捨てるもの' },
      { p: '次のものは執筆前に取り除かれ、人間の判断に回されることもありません。現在または過去の住所、家族・友人・出身校、リアルタイムの移動や目撃情報、アーティストの行きつけとされる場所の未確認情報、私的な交際や健康、実名に紐づく医療・美容施術の主張、つきまといを可能にしうる経路、未成年者の個人情報、権利関係が不明な画像。' },
      { h2: '写真と画像' },
      { p: 'ドラマのキャプチャや芸能人の写真は使いません。当サイトの画像は、オープンライセンスの現地写真、自作の地図と図版、販売者提供の商品画像、あるいは図解であることを明示したイラストのいずれかです。すべての画像はライセンス・出所・クレジットを保存しており、三つのうち一つでも欠けたものは公開できません。' },
      { h2: '撮影のヒントについて' },
      { p: '構図の提案をしている箇所は、訪問者が実際に立てる位置の話です。制作側がどこにカメラを据えたかを述べているのではありません。撮影のヒントを載せたページには、その旨を必ず書いています。' },
      { h2: 'ページを古びさせないために' },
      { p: '住所、営業状況、外部リンクは定期的に自動確認しています。料金には確認した日付を付けています。閉店・閉鎖が確定した場合は予約・購入リンクを外し、ロケ地の記録としてのみページを残します。すべての記事に最終確認日を表示しています。' },
      { h2: '訂正' },
      { p: 'どのページからでも誤りをご指摘いただけます。内容に関わる問題が示された場合、訂正を添えて残すのではなく、確認し直すあいだページを公開から下げます。' },
      { h2: 'AIの利用について' },
      { p: '調査、執筆、翻訳、検証はこの方針のもとでAIの支援を受けて行っています。出典は記録しリンクします。AIを使うからといって、このページのルールが緩むことはありません。量が自動化されているからこそ、このルールがあります。' },
    ],
  },
  'zh-hans': {
    title: '编辑方针',
    description: '我们采信哪些来源、如何措辞、以及拒绝发表什么。',
    h1: '编辑方针', updated: '最后更新 2026年8月13日',
    lead: '本页说明 HANKUKIN 上的信息从何而来、如何分级、如何措辞。它写给读者，同时也是发布系统实际运行所依据的规格。',
    blocks: [
      { h2: '我们采信的来源' },
      { ol: ['电视台、制作公司、经纪公司', '艺人与演职人员的官方频道', '韩国观光公社、地方政府、文化机构', '餐厅、酒店、品牌的官方网站', '地图与预订平台', '注明出处的汇总数据，例如 Naver DataLab', '官方采访与有公信力的新闻媒体'] },
      { h2: '我们不当作事实的来源' },
      { ol: ['匿名论坛帖子', '没有自己出处的粉丝博客', '目击报告', '非公开账号', '除了自身简介之外没有任何出处的转载视频'] },
      { h2: '措辞的分级' },
      { p: '一句话有多强，由它的来源决定，而不是由编辑的把握程度决定。本站关于取景地的每一处说法都会带上下列标签之一，标签由系统自动分配：' },
      { ol: ['官方取景地 —— 由制作方或公共机构确认', '官方采访中确认 —— 所链接的采访这样说', '官方社交媒体出现 —— 由官方账号发布', '可靠媒体报道 —— 至少两家有公信力的媒体', '受场景／风格启发 —— 只是相似，不是确认的事实', '附近的推荐体验 —— 我们自己的推荐，与任何艺人无关'] },
      { p: '如果支撑更强标签的证据不足，说法会被自动降级为较弱的一档。反方向的升级不会发生。' },
      { h2: '直接舍弃的内容' },
      { p: '以下内容在动笔之前就被剔除，也不会交给人来裁量：现在或过去的住址；家人、朋友或学校；实时行踪或目击；关于艺人常去何处的未经证实的说法；私人交往或健康状况；与实名相关的医疗或医美说法；可能便于跟踪的路线；任何未成年人的个人信息；以及权利关系不明的图片。' },
      { h2: '照片与图片' },
      { p: '我们不使用剧集截图或艺人照片。本站图片只有四类：开放授权的实地照片、自制的地图与图表、商家提供的商品图，以及明确标注的插图。每张图都记录了授权、来源和署名——三者缺一，便不能发布。' },
      { h2: '关于拍照建议' },
      { p: '凡是我们建议如何取景的地方，说的都是访客实际能站到的位置，而不是在陈述制作方把摄影机架在哪里。带有拍照建议的页面上，我们都会写明这一点。' },
      { h2: '让页面不过期' },
      { p: '地址、营业状态和外链会按计划自动核查。价格都标注核实日期。当一个地方永久关闭时，我们会移除预订和购买链接，页面只作为取景地的记录保留。每篇文章都显示最后核实日期。' },
      { h2: '更正' },
      { p: '你可以从任何页面报告错误。当报告指向实质性问题时，我们会在重新核对期间把页面撤下，而不是挂着一条说明继续放着。' },
      { h2: '关于 AI 的使用' },
      { p: '资料查证、写作、翻译和核对都是在本方针之下借助 AI 完成的。来源会被记录并链接。使用 AI 不会让本页任何一条规则变松——正因为产量是自动化的，这些规则才存在。' },
    ],
  },
};
