// AUTO-GENERATED by scripts/ingest-from-bundle.mjs — do not edit by hand.
// Fetched 2026-08-17. 2612 places across 17 regions.
import type { JourneyOption } from "../../lib/types";
import { seoulGeneratedOptions, seoulGeneratedCoordinates } from "./seoul.generated";
import { busanGeneratedOptions, busanGeneratedCoordinates } from "./busan.generated";
import { gyeongbukGeneratedOptions, gyeongbukGeneratedCoordinates } from "./gyeongbuk.generated";
import { gyeongnamGeneratedOptions, gyeongnamGeneratedCoordinates } from "./gyeongnam.generated";
import { daeguGeneratedOptions, daeguGeneratedCoordinates } from "./daegu.generated";
import { gwangjuGeneratedOptions, gwangjuGeneratedCoordinates } from "./gwangju.generated";
import { daejeonGeneratedOptions, daejeonGeneratedCoordinates } from "./daejeon.generated";
import { jeonbukGeneratedOptions, jeonbukGeneratedCoordinates } from "./jeonbuk.generated";
import { jeonnamGeneratedOptions, jeonnamGeneratedCoordinates } from "./jeonnam.generated";
import { jejuGeneratedOptions, jejuGeneratedCoordinates } from "./jeju.generated";
import { gangwonGeneratedOptions, gangwonGeneratedCoordinates } from "./gangwon.generated";
import { gyeonggiGeneratedOptions, gyeonggiGeneratedCoordinates } from "./gyeonggi.generated";
import { incheonGeneratedOptions, incheonGeneratedCoordinates } from "./incheon.generated";
import { chungnamGeneratedOptions, chungnamGeneratedCoordinates } from "./chungnam.generated";
import { chungbukGeneratedOptions, chungbukGeneratedCoordinates } from "./chungbuk.generated";
import { ulsanGeneratedOptions, ulsanGeneratedCoordinates } from "./ulsan.generated";
import { sejongGeneratedOptions, sejongGeneratedCoordinates } from "./sejong.generated";

export const GENERATED_CITIES: { id: string; ko: string; en: string; options: JourneyOption[] }[] = [
  { id: "seoul", ko: "서울", en: "seoul", options: seoulGeneratedOptions },
  { id: "busan", ko: "부산", en: "busan", options: busanGeneratedOptions },
  { id: "gyeongbuk", ko: "경상북도", en: "gyeongbuk", options: gyeongbukGeneratedOptions },
  { id: "gyeongnam", ko: "경상남도", en: "gyeongnam", options: gyeongnamGeneratedOptions },
  { id: "daegu", ko: "대구", en: "daegu", options: daeguGeneratedOptions },
  { id: "gwangju", ko: "광주", en: "gwangju", options: gwangjuGeneratedOptions },
  { id: "daejeon", ko: "대전", en: "daejeon", options: daejeonGeneratedOptions },
  { id: "jeonbuk", ko: "전북특별자치도", en: "jeonbuk", options: jeonbukGeneratedOptions },
  { id: "jeonnam", ko: "전라남도", en: "jeonnam", options: jeonnamGeneratedOptions },
  { id: "jeju", ko: "제주특별자치도", en: "jeju", options: jejuGeneratedOptions },
  { id: "gangwon", ko: "강원특별자치도", en: "gangwon", options: gangwonGeneratedOptions },
  { id: "gyeonggi", ko: "경기도", en: "gyeonggi", options: gyeonggiGeneratedOptions },
  { id: "incheon", ko: "인천", en: "incheon", options: incheonGeneratedOptions },
  { id: "chungnam", ko: "충청남도", en: "chungnam", options: chungnamGeneratedOptions },
  { id: "chungbuk", ko: "충청북도", en: "chungbuk", options: chungbukGeneratedOptions },
  { id: "ulsan", ko: "울산", en: "ulsan", options: ulsanGeneratedOptions },
  { id: "sejong", ko: "세종특별자치시", en: "sejong", options: sejongGeneratedOptions },
];

/** Every generated coordinate, merged. The map reads this. */
export const GENERATED_COORDINATES: Record<string, { lat: number; lng: number; city: string; ko: string; en: string; rm: string }> = {
  ...seoulGeneratedCoordinates,
  ...busanGeneratedCoordinates,
  ...gyeongbukGeneratedCoordinates,
  ...gyeongnamGeneratedCoordinates,
  ...daeguGeneratedCoordinates,
  ...gwangjuGeneratedCoordinates,
  ...daejeonGeneratedCoordinates,
  ...jeonbukGeneratedCoordinates,
  ...jeonnamGeneratedCoordinates,
  ...jejuGeneratedCoordinates,
  ...gangwonGeneratedCoordinates,
  ...gyeonggiGeneratedCoordinates,
  ...incheonGeneratedCoordinates,
  ...chungnamGeneratedCoordinates,
  ...chungbukGeneratedCoordinates,
  ...ulsanGeneratedCoordinates,
  ...sejongGeneratedCoordinates,
};
