"use client";

import { useTrip } from "../state/TripContext";
import { TripHeading } from "../components/TripHeading";
import { RightNow } from "../components/RightNow";
import { LANGS, loc, locField } from "../i18n";
import { transport, journeyCategories, samplePlans, sampleDays, originLocations, originRegionGroups, requestExamples } from "../data/journey";
import { formatWon } from "../lib/format";
import type { Tab, Stop, JourneyCategory, MapScale, PlannerStage } from "../lib/types";
import { ModePalette } from "./Chrome";

export default function LiveView() {
  const {
    activeRegion,
    addDestination,
    addSelectedOptions,
    analyzeRequest,
    budgetRemaining,
    buildMapScope,
    changeDetailAddress,
    changeOriginArea,
    changeOriginCity,
    changeOriginCountry,
    citiesMissingData,
    composeOrigin,
    costLines,
    costMax,
    costTotals,
    dayCondition,
    dayLimitMinutes,
    decision,
    destinationCoverage,
    destinationInput,
    destinationQuery,
    destinations,
    detailAddress,
    docOpen,
    durationText,
    easyOnly,
    extension,
    extraBudget,
    filteredJourneyOptions,
    freeOnly,
    homeAirportMode,
    inputAnalyzed,
    itinerary,
    journeyOptions,
    lang,
    late,
    legAmounts,
    locationStatus,
    mapScale,
    maxOptionMinutes,
    mode,
    moveStop,
    moving,
    optionCategory,
    optionSearch,
    origin,
    originArea,
    originChoice,
    originCity,
    originCountry,
    originCountryQuery,
    originRegion,
    parkingPerDay,
    plannerStage,
    projectedCost,
    projectedTime,
    purposes,
    requestText,
    ride,
    rides,
    routeAddedCost,
    routeAddedTime,
    sameOnReturn,
    selectedCityData,
    selectedCountryData,
    selectedDay,
    selectedDayData,
    selectedJourneyOptions,
    selectedMapNodes,
    selectedOptionIds,
    selectedPlan,
    selectedPlanData,
    selectionCost,
    selectionTime,
    setActiveRegion,
    setBuildMapScope,
    setDayCondition,
    setDayLimitMinutes,
    setDecision,
    setDestinationInput,
    setDestinationQuery,
    setDestinations,
    setDetailAddress,
    setDocOpen,
    setEasyOnly,
    setExtension,
    setExtraBudget,
    setFreeOnly,
    setHomeAirportMode,
    setInputAnalyzed,
    setItinerary,
    setLang,
    setLate,
    setLegAmount,
    setLegAmounts,
    setLocationStatus,
    setMapScale,
    setMaxOptionMinutes,
    setMode,
    setMoving,
    setOptionCategory,
    setOptionSearch,
    setOrigin,
    setOriginArea,
    setOriginChoice,
    setOriginCity,
    setOriginCountry,
    setOriginCountryQuery,
    setOriginRegion,
    setParkingPerDay,
    setPlannerStage,
    setPurposes,
    setRequestText,
    setRide,
    setSameOnReturn,
    setSelectedDay,
    setSelectedOptionIds,
    setSelectedPlan,
    setShowDetails,
    setStayStrategy,
    setStops,
    setSubmitted,
    setTab,
    setTransferMode,
    showDetails,
    stayStrategy,
    stops,
    submitted,
    t,
    tab,
    tf,
    timeRemaining,
    toggleDestination,
    toggleJourneyOption,
    toggleLock,
    togglePurpose,
    transferMode,
    useCurrentLocation,
    visibleDestinationRegions,
    addedByDay,addToToday,todayIndex,themes,selectedGeneratedPlan,
    visibleOriginCountries,
  } = useTrip();
  return <>
    <section className="trip-heading"><TripHeading lang={lang} origin={originCity==="hyderabad"?"":originCity} destinations={destinations} onToggleDestination={toggleDestination} party={4}/><div className="weather-token"><span>{t("clear")}</span><strong>24°</strong></div></section>
    <section className="pulse-card"><div className="pulse-topline"><span className="live-dot"/><p>{moving?(t("in_transit")):t("copy_greeting")}</p></div><div className="pulse-grid"><div><h2>{moving?(t("you_re_on_the_way_to_seoul")):late?(t("your_journey_has_been_recalculated")):t("copy_leave")}</h2><p>{moving?(t("we_re_refreshing_your_eta_and_protecting")):late?(t("fixed_bookings_are_protected_while_travel_and")):t("copy_leave_sub")}</p></div><div className="countdown"><span>{moving?(t("status")):t("copy_countdown")}</span><strong>{moving?(t("moving")):late?(t("now")):t("copy_minutes")}</strong></div></div><div className="pulse-actions"><button className="primary-action" onClick={()=>{setMoving(true);setDecision(null)}}>{moving?(t("current_route")):(t("start_moving"))}<span>→</span></button>{!moving&&<button className="quiet-action" onClick={()=>setDecision("extend")}>{t("stay_longer")}</button>}<button className="quiet-action" onClick={()=>setLate(v=>!v)}>{moving?(t("travel_issue")):t("copy_delay")}</button></div></section>
    {/* The plan and the improvisation are the same object. This panel asks the
        chain what fits between now and bedtime — the identical subtraction the
        planner ran weeks ago against a gap it could only guess the shape of. */}
    <RightNow lang={lang}
      city={selectedGeneratedPlan?.days[Math.min(todayIndex,selectedGeneratedPlan.days.length)-1]?.city ?? destinations[0] ?? ""}
      themes={themes}
      planned={new Set((selectedGeneratedPlan?.days.flatMap(d=>d.stops)??[]).map(o=>o.id))}
      added={addedByDay[todayIndex]??[]}
      onAdd={addToToday}/>
    <section className="content-grid"><div className="main-column">
      <article className="booking-card"><div className="section-label">{t("copy_next_booking")}</div><div className="booking-body"><div className="time-block"><strong>08:30</strong><span>BOARD</span></div><div className="booking-copy"><h3>{t("copy_train")}</h3><p>{t("copy_train_meta")}</p></div><div className="booking-tools"><span className="fixed-tag">{t("copy_fixed")}</span><button onClick={()=>setDocOpen("ktx")}>{t("open_ticket")}</button></div></div></article>
      <section className="choice-section"><div className="section-heading"><div><span>NOW</span><h2>{t("copy_current_leg")}</h2></div><p>{t("copy_choice_help")}</p></div><div className="ride-list">{rides.map(item=><button key={item.id} className={`ride-card ${ride===item.id?"selected":""}`} onClick={()=>setRide(item.id)}><span className="ride-number">{item.mark}</span><span className="ride-copy"><strong>{item.title}</strong><small>{item.meta}</small></span><span className="radio"><i/></span>{ride===item.id&&<em>{t("copy_selected")}</em>}</button>)}</div></section>
      <article className="arrival-card"><div className="arrival-time">−10</div><div><span>AUTO ALERT</span><h3>{t("copy_after_arrival")}</h3><p>{t("copy_after_arrival_meta")}</p></div></article>
    </div><aside className="side-column"><div className="side-title"><span>{t("copy_next")}</span><strong>02</strong></div><article className="next-card route"><span className="mini-label">TRANSFER</span><h3>{t("copy_gy")}</h3><p>{t("copy_gy_meta")}</p><button>COMPARE →</button></article><article className="next-card food"><span className="mini-label">{t("copy_food")}</span><h3>{t("copy_food_title")}</h3><p>{t("copy_food_meta")}</p><div className="food-tags"><span>MENU</span><span>PRICE</span><span>ORDER</span></div></article><article className="next-card stay"><span className="mini-label">CHECK-IN</span><h3>{t("copy_stay")}</h3><p>{t("copy_stay_meta")}</p></article></aside></section>
  </>;
}
