"use client";

import { useTrip } from "../state/TripContext";
import { LANGS, loc, locField } from "../i18n";
import { transport, journeyCategories, samplePlans, sampleDays, originLocations, originRegionGroups, destinationRegions, requestExamples, type OriginCountry } from "../data/journey";

const QUICK_START_KEYS = ["quick_first_family_trip","quick_beauty_shopping","quick_regional_heritage"] as const;
import { formatWon } from "../lib/format";
import { routeText } from "../lib/plan-generator";
import { cityLabel } from "../data/places";
import { DoorLegPicker } from "../components/DoorLegPicker";
import { UnknownLineFiller } from "../components/UnknownLineFiller";
import { AffiliateSlot, AffiliateDisclosure } from "../components/AffiliateSlot";
import type { Tab, Stop, JourneyCategory, MapScale, PlannerStage } from "../lib/types";


/** Top-level component. Declaring this inside PlanView would remount it
 *  on every keystroke — the original Hangul focus bug. */
function PlannerInput() {
  const {
    activeRegion,
    addDestination,
    addSelectedOptions,
    analyzeRequest,
    budgetRemaining,
    buildMapScope,
    changeDetailAddress,
    changeOriginArea,
    changeOriginCity,
    changeOriginCountry,
    citiesMissingData,
    composeOrigin,
    costLines,
    costMax,
    costTotals,
    dayCondition,
    dayLimitMinutes,
    decision,
    destinationCoverage,
    destinationInput,
    destinationQuery,
    destinations,
    detailAddress,
    docOpen,
    durationText,
    easyOnly,
    extension,
    extraBudget,
    filteredJourneyOptions,
    freeOnly,
    selectedGeneratedPlan,
    generatedPlans,
    homeAirportMode,
    inputAnalyzed,
    itinerary,
    journeyOptions,
    lang,
    late,
    legAmounts,
    locationStatus,
    mapScale,
    maxOptionMinutes,
    mode,
    moveStop,
    moving,
    optionCategory,
    optionSearch,
    origin,
    originArea,
    originChoice,
    originCity,
    originCountry,
    originCountryQuery,
    originRegion,
    parkingPerDay,
    plannerStage,
    projectedCost,
    projectedTime,
    purposes,
    requestText,
    ride,
    rides,
    routeAddedCost,
    routeAddedTime,
    sameOnReturn,
    selectedCityData,
    selectedCountryData,
    selectedDay,
    selectedDayData,
    selectedJourneyOptions,
    selectedMapNodes,
    selectedOptionIds,
    selectedPlan,
    selectedPlanData,
    selectionCost,
    selectionTime,
    setActiveRegion,
    setBuildMapScope,
    setDayCondition,
    setDayLimitMinutes,
    setDecision,
    setDestinationInput,
    setDestinationQuery,
    setDestinations,
    setDetailAddress,
    setDocOpen,
    setEasyOnly,
    setExtension,
    setExtraBudget,
    setFreeOnly,
    setHomeAirportMode,
    setInputAnalyzed,
    setItinerary,
    setLang,
    setLate,
    setLegAmount,
    setLegAmounts,
    setLocationStatus,
    setMapScale,
    setMaxOptionMinutes,
    setMode,
    setMoving,
    setOptionCategory,
    setOptionSearch,
    setOrigin,
    setOriginArea,
    setOriginChoice,
    setOriginCity,
    setOriginCountry,
    setOriginCountryQuery,
    setOriginRegion,
    setParkingPerDay,
    setPlannerStage,
    setPurposes,
    setRequestText,
    setRide,
    setSameOnReturn,
    setSelectedDay,
    setSelectedOptionIds,
    setSelectedPlan,
    setShowDetails,
    setStayStrategy,
    setStops,
    setSubmitted,
    setTab,
    setTransferMode,
    showDetails,
    stayStrategy,
    stops,
    submitted,
    t,
    tab,
    tf,
    timeRemaining,
    toggleDestination,
    toggleJourneyOption,
    toggleLock,
    togglePurpose,
    transferMode,
    useCurrentLocation,
    visibleDestinationRegions,
    visibleOriginCountries,
  } = useTrip();
  return <>
    <div className="workspace-hero planner-hero"><span>PLAN FROM YOUR DOOR</span><h1>{t("start_your_journey_in_one_sentence")}</h1><p>{t("no_need_to_fill_every_field_describe")}</p></div>
    <div className="planner-layout"><div className="planner-form">
      <article className="easy-planner"><div className="origin-question"><div><span>STARTING POINT</span><strong>{t("are_you_leaving_from_where_you_are")}</strong><p>{t("choosing_yes_asks_for_browser_location_permission")}</p></div><div className="origin-choice-buttons"><button className={originChoice==="current"?"active":""} onClick={useCurrentLocation}>⌖ {locationStatus==="loading"?(t("locating")):(t("yes_use_current_location"))}</button><button className={originChoice==="manual"?"active":""} onClick={()=>{setOriginChoice("manual");setLocationStatus("idle");setOrigin(composeOrigin(originCountry,originCity,originArea,detailAddress));}}>⌂ {t("no_choose_another_place")}</button></div>{originChoice==="manual"&&<div className="address-builder"><div className="address-builder-title"><span>{t("where_are_you_now")}</span><small>{t("choose_worldwide_region_country_city_area_and")}</small></div><div className="global-origin-tools"><div className="origin-region-tabs">{originRegionGroups.map(region=><button key={region.id} className={originRegion===region.id?"active":""} onClick={()=>setOriginRegion(region.id)}>{loc(lang, region)}</button>)}</div><label><span>{t("search_country")}</span><input value={originCountryQuery} onChange={e=>setOriginCountryQuery(e.target.value)} placeholder={t("e_g_india_china_brazil")}/></label></div><div className="global-origin-count"><b>{Object.keys(originLocations).length} COUNTRIES</b><span>{t("priority_cities_included_type_any_missing_location")}</span></div><div className="address-fields"><label>{t("country")}<select value={originCountry} onChange={e=>changeOriginCountry(e.target.value as OriginCountry)}>{visibleOriginCountries.map(id=><option value={id} key={id}>{loc(lang, originLocations[id])}</option>)}</select></label><label>{t("city")}<select value={originCity} onChange={e=>changeOriginCity(e.target.value)}>{selectedCountryData.cities.map(city=><option value={city.id} key={city.id}>{loc(lang, city)}</option>)}</select></label><label>{t("area")}<select value={originArea} onChange={e=>changeOriginArea(e.target.value)}>{selectedCityData.areas.map(area=><option value={area} key={area}>{area}</option>)}</select></label><label className="exact-address">{t("address_building")}<input value={detailAddress} onChange={e=>changeDetailAddress(e.target.value)} placeholder={t("street_building_or_any_city_not_listed")}/></label></div><div className="composed-address"><b>PINNED ORIGIN</b><span>{origin}</span></div></div>}</div><div className="easy-planner-head"><span>AI TRIP BRIEF</span><strong>{t("describe_the_rest_in_one_sentence")}</strong><p>{t("add_desired_cities_dates_party_and_purpose")}</p></div><textarea value={requestText} onChange={e=>{setRequestText(e.target.value);setInputAnalyzed(false);}} placeholder={t("example_a_family_of_four_wants_7")} aria-label={t("describe_your_trip")}/><div className="example-prompts"><span>{t("tap_an_example")}</span>{requestExamples.map((example,index)=><button key={example} onClick={()=>{setRequestText(example);analyzeRequest(example);}}>{t(QUICK_START_KEYS[index])}</button>)}</div><div className="easy-actions"><button className="destination-open" onClick={()=>setShowDetails(true)}>{t("select_multiple_korean_cities")}</button><button className="analyze-button" disabled={!requestText.trim()} onClick={()=>analyzeRequest()}>{t("organize_my_trip")}<span>→</span></button></div></article>
      {inputAnalyzed&&<article className="brief-result"><div><span>TRIP BRIEF READY</span><strong>{t("here_is_what_we_understood")}</strong></div><div className="brief-grid"><p><b>{t("from")}</b>{origin}</p><p><b>{t("visit")}</b>{destinations.join(" · ")}</p><p><b>{t("stays")}</b>{stayStrategy==="hub"?(t("one_seoul_base")):stayStrategy==="direct"?(t("direct_to_region")):stayStrategy==="split"?(t("split_by_region")):(t("ai_recommended"))}</p><p><b>{t("purpose")}</b>{purposes.length?purposes.map(id=>({beauty:"뷰티",medical:"의료",culture:"문화재",sight:"관광",theme:"테마파크",water:"워터파크",shopping:"쇼핑",seoul:"서울문화",food:"음식",mixed:"복합"} as Record<string,string>)[id]||id).join(" · "):(t("open"))}</p></div><button onClick={()=>setShowDetails(true)}>{t("edit_only_what_is_wrong")} →</button></article>}
      <button className="detail-toggle" onClick={()=>setShowDetails(v=>!v)}><span>{showDetails?(t("hide_detailed_inputs")):(t("set_details_manually"))}</span><b>{showDetails?"−":"+"}</b></button>
      {showDetails&&<div className="detail-inputs"><article className="planner-section"><div className="planner-step"><b>01</b><div><span>DOOR & DESTINATIONS</span><h2>{t("origin_and_korean_destinations")}</h2></div></div><div className="origin-confirmation"><div><b>{t("current_origin")}</b><span>{origin}</span></div><button onClick={()=>{setOriginChoice("manual");window.scrollTo({top:0,behavior:"smooth"});}}>{t("change_origin")}</button></div><div className="return-row"><span>{t("return_to_the_same_first_departure_point")}</span><strong>ROUND TRIP</strong></div><div className="destination-selector-head"><div><strong>{t("select_every_korean_city_you_want_to")}</strong><span>{tf("n_0_selected",destinations.length)}</span></div><input value={destinationQuery} onChange={e=>setDestinationQuery(e.target.value)} placeholder={t("search_city")} aria-label={t("search_korean_cities")}/></div><div className="region-tabs"><button className={activeRegion==="all"?"active":""} onClick={()=>setActiveRegion("all")}>{t("all")}</button>{destinationRegions.map(region=><button key={region.id} className={activeRegion===region.id?"active":""} onClick={()=>setActiveRegion(region.id)}>{loc(lang, region)}</button>)}</div><div className="korea-city-groups">{visibleDestinationRegions.map(region=><section key={region.id}><span>{loc(lang, region)}</span><div>{region.cities.map(city=><button key={city} className={destinations.includes(city)?"active":""} onClick={()=>toggleDestination(city)}><i>{destinations.includes(city)?"✓":"+"}</i>{city}</button>)}</div></section>)}</div><div className="custom-place"><label className="field-label">{t("add_a_place_not_listed")}<div className="destination-entry"><input value={destinationInput} onChange={e=>setDestinationInput(e.target.value)} onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(e.key==="Enter"){e.preventDefault();addDestination();}}} placeholder={t("city_attraction_clinic_or_theme_park")}/><button onClick={addDestination}>+ {t("add")}</button></div></label></div><div className="destination-chips selected-city-chips"><b>{t("selected")}</b>{destinations.map(place=><button key={place} onClick={()=>setDestinations(destinations.filter(x=>x!==place))}>{place}<span>×</span></button>)}</div></article>
      <article className="planner-section"><div className="planner-step"><b>02</b><div><span>DATES & PARTY</span><h2>{t("dates_and_travelers")}</h2></div></div><div className="field-grid"><label className="field-label">{t("departure")}<input type="date" defaultValue="2026-10-10"/></label><label className="field-label">{t("return")}<input type="date" defaultValue="2026-10-17"/></label><label className="field-label">{t("travelers")}<select defaultValue="4"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5+</option></select></label><label className="field-label">{t("target_total_budget")}<select defaultValue="800"><option value="600">₩6M</option><option value="800">₩8M</option><option value="1000">₩10M</option><option value="open">{t("open")}</option></select></label></div></article>
      <article className="planner-section"><div className="planner-step"><b>03</b><div><span>STAY STRATEGY</span><h2>{t("how_should_your_stays_work")}</h2></div></div><div className="stay-options">{[
        ["hub",t("seoul_hub"),t("no_bag_moves_longer_day_trips")],
        ["split",t("split_by_region_2"),t("more_visit_time_more_checkouts")],
        ["direct",t("direct_to_region"),t("region_first_harder_arrival_day")],
        ["ai",t("ai_decides"),t("optimize_cost_time_and_purpose")],
      ].map(([id,title,meta])=><button key={id} className={stayStrategy===id?"active":""} onClick={()=>setStayStrategy(id)}><strong>{title}</strong><span>{meta}</span></button>)}</div></article>
      <article className="planner-section"><div className="planner-step"><b>04</b><div><span>TRAVEL PURPOSE</span><h2>{t("purpose_of_this_journey")}</h2></div></div><div className="purpose-options">{[
        ["beauty","BEAUTY",t("beauty")],["medical","MEDICAL",t("medical")],["culture","HERITAGE",t("heritage")],["sight","SIGHTS",t("sightseeing")],["theme","THEME",t("theme_parks")],["water","WATER",t("water_parks")],["shopping","SHOP",t("shopping")],["seoul","SEOUL",t("seoul_culture")],["food","FOOD",t("food")],["mixed","MIXED",t("mixed")],
      ].map(([id,code,label])=><button key={id} className={purposes.includes(id)?"active":""} onClick={()=>togglePurpose(id)}><i>{code}</i><span>{label}</span></button>)}</div></article></div>}
      <button className="generate-plans" disabled={originChoice==="ask"||!destinations.length} onClick={()=>setPlannerStage("results")}><span>{originChoice==="ask"?(t("choose_your_origin_first")):(t("see_10_plans_for_this_trip"))}</span><b>{t("compare_edit_next")} →</b></button>
    </div><aside className="planner-summary"><article className="dark-panel sticky-panel"><span>WHAT YOU WILL GET</span><h3>{t("10_plans_with_distinct_routes_and_costs")}</h3><ul><li>{t("total_per_person_and_itemized_costs")}</li><li>{t("stay_locations_with_pros_and_cons")}</li><li>{t("korea_regional_and_street_level_maps")}</li><li>{t("time_based_route_for_every_day")}</li><li>{t("walking_exits_and_transfer_guidance")}</li></ul><div className="simulation-note">{t("current_prices_and_routes_are_product_examples")}</div></article></aside></div>
  </>;
}

/** Top-level component. Declaring this inside PlanView would remount it
 *  on every keystroke — the original Hangul focus bug. */
function PlannerResults() {
  const {
    activeRegion,
    addDestination,
    addSelectedOptions,
    analyzeRequest,
    budgetRemaining,
    buildMapScope,
    changeDetailAddress,
    changeOriginArea,
    changeOriginCity,
    changeOriginCountry,
    citiesMissingData,
    composeOrigin,
    costLines,
    costMax,
    costTotals,
    dayCondition,
    dayLimitMinutes,
    decision,
    destinationCoverage,
    destinationInput,
    destinationQuery,
    destinations,
    detailAddress,
    docOpen,
    durationText,
    easyOnly,
    extension,
    extraBudget,
    filteredJourneyOptions,
    freeOnly,
    selectedGeneratedPlan,
    generatedPlans,
    homeAirportMode,
    inputAnalyzed,
    itinerary,
    journeyOptions,
    lang,
    late,
    legAmounts,
    locationStatus,
    mapScale,
    maxOptionMinutes,
    mode,
    moveStop,
    moving,
    optionCategory,
    optionSearch,
    origin,
    originArea,
    originChoice,
    originCity,
    originCountry,
    originCountryQuery,
    originRegion,
    parkingPerDay,
    plannerStage,
    projectedCost,
    projectedTime,
    purposes,
    requestText,
    ride,
    rides,
    routeAddedCost,
    routeAddedTime,
    sameOnReturn,
    selectedCityData,
    selectedCountryData,
    selectedDay,
    selectedDayData,
    selectedJourneyOptions,
    selectedMapNodes,
    selectedOptionIds,
    selectedPlan,
    selectedPlanData,
    selectionCost,
    selectionTime,
    setActiveRegion,
    setBuildMapScope,
    setDayCondition,
    setDayLimitMinutes,
    setDecision,
    setDestinationInput,
    setDestinationQuery,
    setDestinations,
    setDetailAddress,
    setDocOpen,
    setEasyOnly,
    setExtension,
    setExtraBudget,
    setFreeOnly,
    setHomeAirportMode,
    setInputAnalyzed,
    setItinerary,
    setLang,
    setLate,
    setLegAmount,
    setLegAmounts,
    setLocationStatus,
    setMapScale,
    setMaxOptionMinutes,
    setMode,
    setMoving,
    setOptionCategory,
    setOptionSearch,
    setOrigin,
    setOriginArea,
    setOriginChoice,
    setOriginCity,
    setOriginCountry,
    setOriginCountryQuery,
    setOriginRegion,
    setParkingPerDay,
    setPlannerStage,
    setPurposes,
    setRequestText,
    setRide,
    setSameOnReturn,
    setSelectedDay,
    setSelectedOptionIds,
    setSelectedPlan,
    setShowDetails,
    setStayStrategy,
    setStops,
    setSubmitted,
    setTab,
    setTransferMode,
    showDetails,
    stayStrategy,
    stops,
    submitted,
    t,
    tab,
    tf,
    timeRemaining,
    toggleDestination,
    toggleJourneyOption,
    toggleLock,
    togglePurpose,
    transferMode,
    useCurrentLocation,
    visibleDestinationRegions,
    visibleOriginCountries,
  } = useTrip();
  return <>
    <div className="results-head"><button onClick={()=>setPlannerStage("input")}>← {t("edit_inputs")}</button><div><span>10 ROUTES GENERATED</span><h1>{origin} → {destinations.join(" · ")}</h1><p>{t("each_plan_uses_materially_different_priorities_for")}</p></div></div>
    <div className="result-notice"><strong>{t("product_cost_simulation")}</strong><span>{t("example_amounts_before_live_air_stay_and")}</span></div>
    <div className="plans-grid">{generatedPlans.map((plan,index)=>{
      const copy=plan.strategy.labels[lang];
      return <article className={`plan-card ${index===0?"recommended":""}`} key={plan.id}>
        <div className="plan-card-top"><span>{String(index+1).padStart(2,"0")}</span><em>{copy.tag}</em></div>
        <h2>{copy.title}</h2>
        <p>{routeText(plan,t("night_short"))}</p>
        {/* What you get and what it costs you. Both, or neither is useful. */}
        <div className="plan-tradeoff"><span className="gives">{copy.gives}</span><span className="costs">{copy.costs}</span></div>
        <div className="plan-metrics">
          <span>{t("places")} <b>{plan.placeCount}</b></span>
          <span>{t("stay_moves")} <b>{plan.stayChanges}</b></span>
          <span>{t("time_on_the_move")} <b>{durationText(plan.minutes)}</b></span>
        </div>
        {/* No total. The ingested places are not priced yet, and a number here
            would be the most confident thing on the card and the least true. */}
        <p className="plan-unpriced">{plan.priced>0?tf("0_of_1_places_have_a_published_fee",plan.priced,plan.placeCount):t("no_published_fees_yet")}</p>
        <button onClick={()=>{setSelectedPlan(index);setSelectedDay(0);setMapScale("korea");setPlannerStage("detail")}}>{t("view_daily_map_costs")} →</button>
      </article>;
    })}</div>
    {generatedPlans.length===0 && <div className="empty-state"><strong>{t("choose_a_korean_city_first")}</strong><p>{t("options_appear_once_you_pick_cities")}</p></div>}
  </>;
}


/** Top-level component. Declaring this inside PlanView would remount it
 *  on every keystroke — the original Hangul focus bug. */
function PlannerDetail() {
  const {
    activeRegion,
    addDestination,
    addSelectedOptions,
    analyzeRequest,
    budgetRemaining,
    buildMapScope,
    changeDetailAddress,
    changeOriginArea,
    changeOriginCity,
    changeOriginCountry,
    citiesMissingData,
    composeOrigin,
    costLines,
    costMax,
    costTotals,
    dayCondition,
    dayLimitMinutes,
    decision,
    destinationCoverage,
    destinationInput,
    destinationQuery,
    destinations,
    detailAddress,
    docOpen,
    durationText,
    easyOnly,
    extension,
    extraBudget,
    filteredJourneyOptions,
    freeOnly,
    selectedGeneratedPlan,
    generatedPlans,
    homeAirportMode,
    inputAnalyzed,
    itinerary,
    journeyOptions,
    lang,
    late,
    legAmounts,
    locationStatus,
    mapScale,
    maxOptionMinutes,
    mode,
    moveStop,
    moving,
    optionCategory,
    optionSearch,
    origin,
    originArea,
    originChoice,
    originCity,
    originCountry,
    originCountryQuery,
    originRegion,
    parkingPerDay,
    plannerStage,
    projectedCost,
    projectedTime,
    purposes,
    requestText,
    ride,
    rides,
    routeAddedCost,
    routeAddedTime,
    sameOnReturn,
    selectedCityData,
    selectedCountryData,
    selectedDay,
    selectedDayData,
    selectedJourneyOptions,
    selectedMapNodes,
    selectedOptionIds,
    selectedPlan,
    selectedPlanData,
    selectionCost,
    selectionTime,
    setActiveRegion,
    setBuildMapScope,
    setDayCondition,
    setDayLimitMinutes,
    setDecision,
    setDestinationInput,
    setDestinationQuery,
    setDestinations,
    setDetailAddress,
    setDocOpen,
    setEasyOnly,
    setExtension,
    setExtraBudget,
    setFreeOnly,
    setHomeAirportMode,
    setInputAnalyzed,
    setItinerary,
    setLang,
    setLate,
    setLegAmount,
    setLegAmounts,
    setLocationStatus,
    setMapScale,
    setMaxOptionMinutes,
    setMode,
    setMoving,
    setOptionCategory,
    setOptionSearch,
    setOrigin,
    setOriginArea,
    setOriginChoice,
    setOriginCity,
    setOriginCountry,
    setOriginCountryQuery,
    setOriginRegion,
    setParkingPerDay,
    setPlannerStage,
    setPurposes,
    setRequestText,
    setRide,
    setSameOnReturn,
    setSelectedDay,
    setSelectedOptionIds,
    setSelectedPlan,
    setShowDetails,
    setStayStrategy,
    setStops,
    setSubmitted,
    setTab,
    setTransferMode,
    showDetails,
    stayStrategy,
    stops,
    submitted,
    t,
    tab,
    tf,
    timeRemaining,
    toggleDestination,
    toggleJourneyOption,
    toggleLock,
    togglePurpose,
    transferMode,
    useCurrentLocation,
    visibleDestinationRegions,
    visibleOriginCountries,
  } = useTrip();
  return <>
    <div className="detail-head"><button onClick={()=>setPlannerStage("results")}>← {t("all_10_plans")}</button><div><span>{selectedGeneratedPlan?.strategy.labels[lang].tag} · PLAN {String(selectedPlan+1).padStart(2,"0")}</span><h1>{selectedGeneratedPlan?.strategy.labels[lang].title}</h1><p>{selectedGeneratedPlan?routeText(selectedGeneratedPlan,t("night_short")):""}</p></div><div className="detail-total"><span>{t("total_4_people")}</span><strong>{formatWon(costTotals.total)}</strong><small>{costTotals.incomplete?t("total_so_far"):t("example_estimate_not_live")}</small></div></div>
    <div className="detail-grid"><div className="detail-main">
      <article className="panel cost-panel"><div className="panel-head"><div><span>ITEMIZED COST</span><h2>{t("estimated_cost_breakdown")}</h2></div><small>{t("reconciled")}</small></div><div className="cost-rows">{costLines.map(line=><div key={line.id} className={line.amount===null?"cost-unknown":""}>
            <span>{line.labels[lang]}</span>
            <i><b style={{width:`${((line.amount??0)/costMax)*100}%`}}/></i>
            <strong>{line.amount===null?t("not_estimated_yet"):formatWon(line.amount)}</strong>
            <AffiliateSlot lang={lang} lineId={line.id} surface="plan"/>
          </div>)}</div>
          {costTotals.incomplete && <p className="cost-incomplete">{t("cost_incomplete_notice")}</p>}
          <AffiliateDisclosure lang={lang}/>
          <DoorLegPicker lang={lang} mode={homeAirportMode} onMode={setHomeAirportMode}
            parkingPerDay={parkingPerDay} onParkingPerDay={setParkingPerDay}
            departISO="2026-10-10" returnISO="2026-10-17"/>
          <UnknownLineFiller lang={lang} amounts={legAmounts} onAmount={setLegAmount}
            transferMode={transferMode} onTransferMode={setTransferMode}
            sameOnReturn={sameOnReturn} onSameOnReturn={setSameOnReturn}/></article>
      <article className="panel lodging-panel"><div className="panel-head"><div><span>STAY LOGIC</span><h2>{t("stay_location_drives_the_route")}</h2></div><small>{locField(lang, selectedPlanData, "hotel")}</small></div><div className="lodging-compare"><div><strong>{t("advantages")}</strong><p>{t("preserves_time_at_each_region_and_reduces")}</p></div><div><strong>{t("trade_offs")}</strong><p>{t("checkout_luggage_movement_and_each_check_in")}</p></div></div></article>
      <article className="panel journey-map-panel"><div className="map-panel-head"><div><span>DAY-BY-DAY MAP</span><h2>{t("map_and_timeline_move_together")}</h2></div><div className="map-scale">{(["korea","city","street"] as MapScale[]).map(scale=><button key={scale} className={mapScale===scale?"active":""} onClick={()=>setMapScale(scale)}>{scale==="korea"?(t("korea_2")):scale==="city"?(t("city_2")):(t("street"))}</button>)}</div></div><div className="day-tabs">{(selectedGeneratedPlan?.days??[]).map((day,index)=><button key={day.n} className={selectedDay===index?"active":""} onClick={()=>{setSelectedDay(index);setMapScale("city")}}><b>D{day.n}</b><span>{cityLabel(day.city)}</span></button>)}</div><div className="map-and-time"><div className={`route-map ${mapScale}`}><div className="map-watermark">{mapScale==="korea"?"KOREA ROUTE":mapScale==="city"?"REGIONAL DAY MAP":"LAST-MILE ACCESS"}</div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline points={selectedMapNodes.map(n=>`${n.x},${n.y}`).join(" ")}/></svg>{selectedMapNodes.map((node,index)=><div key={node.en} className="map-node" style={{left:`${node.x}%`,top:`${node.y}%`}}><b>{index+1}</b><span>{loc(lang, node)}</span></div>)}<div className="map-source">{t("map_api_pending_conceptual_positions_only")}</div></div><div className="day-timeline"><div className="timeline-title"><span>DAY {selectedDay+1}</span><strong>{cityLabel(selectedGeneratedPlan?.days[selectedDay]?.city ?? "")}</strong></div>{(selectedGeneratedPlan?.days[selectedDay]?.stops??[]).map((stop,index,arr)=><div className="timeline-row" key={stop.id}><time>{durationText(arr.slice(0,index).reduce((m,s)=>m+s.stayMinutes+s.transferMinutes,0))}</time><i/><div><strong>{loc(lang, stop)}</strong><em className="place-hangul" lang="ko">{stop.ko}</em><span>{locField(lang, stop, "hours")}</span></div></div>)}<p className="timeline-note">{t("times_are_our_estimate_not_a_schedule")}</p></div></div></article>
      <article className="panel access-panel"><div className="panel-head"><div><span>ACCESS GUIDE</span><h2>{t("from_station_exit_to_the_exact_entrance")}</h2></div><small>{t("official_field_verified")}</small></div><div className="access-steps">{[
        ["EXIT",t("subway_exit_elevator")],["CROSS",t("crosswalk_road_crossing")],["STOP",t("stop_id_route_headsign")],["PLATFORM",t("platform_transfer_path_boarding_position")],["DOOR",t("exact_hotel_clinic_or_attraction_entrance")],
      ].map(([code,label],index)=><div key={code}><b>{String(index+1).padStart(2,"0")}</b><span><i>{code}</i><strong>{label}</strong></span><em>{t("show_after_data_connection")}</em></div>)}</div><p className="verification-note">{t("ai_never_invents_unverified_exits_crossings_or")}</p></article>
    </div><aside className="detail-side"><article className="dark-panel sticky-panel"><span>PLAN SCORE</span><h3>{selectedPlanData.score} / 100</h3><p>{t("example_composite_score_for_cost_travel_time")}</p><ul><li>{t("desired_places_3_3")}</li><li>{t("2_stay_changes")}</li><li>{tf("average_walk_0",selectedPlanData.walk)}</li></ul><button className="select-plan" onClick={()=>setTab("build")}>{t("select_and_customize")} →</button></article></aside></div>
  </>;
}

export default function PlanView() {
  const {
    activeRegion,
    addDestination,
    addSelectedOptions,
    analyzeRequest,
    budgetRemaining,
    buildMapScope,
    changeDetailAddress,
    changeOriginArea,
    changeOriginCity,
    changeOriginCountry,
    citiesMissingData,
    composeOrigin,
    costLines,
    costMax,
    costTotals,
    dayCondition,
    dayLimitMinutes,
    decision,
    destinationCoverage,
    destinationInput,
    destinationQuery,
    destinations,
    detailAddress,
    docOpen,
    durationText,
    easyOnly,
    extension,
    extraBudget,
    filteredJourneyOptions,
    freeOnly,
    selectedGeneratedPlan,
    generatedPlans,
    homeAirportMode,
    inputAnalyzed,
    itinerary,
    journeyOptions,
    lang,
    late,
    legAmounts,
    locationStatus,
    mapScale,
    maxOptionMinutes,
    mode,
    moveStop,
    moving,
    optionCategory,
    optionSearch,
    origin,
    originArea,
    originChoice,
    originCity,
    originCountry,
    originCountryQuery,
    originRegion,
    parkingPerDay,
    plannerStage,
    projectedCost,
    projectedTime,
    purposes,
    requestText,
    ride,
    rides,
    routeAddedCost,
    routeAddedTime,
    sameOnReturn,
    selectedCityData,
    selectedCountryData,
    selectedDay,
    selectedDayData,
    selectedJourneyOptions,
    selectedMapNodes,
    selectedOptionIds,
    selectedPlan,
    selectedPlanData,
    selectionCost,
    selectionTime,
    setActiveRegion,
    setBuildMapScope,
    setDayCondition,
    setDayLimitMinutes,
    setDecision,
    setDestinationInput,
    setDestinationQuery,
    setDestinations,
    setDetailAddress,
    setDocOpen,
    setEasyOnly,
    setExtension,
    setExtraBudget,
    setFreeOnly,
    setHomeAirportMode,
    setInputAnalyzed,
    setItinerary,
    setLang,
    setLate,
    setLegAmount,
    setLegAmounts,
    setLocationStatus,
    setMapScale,
    setMaxOptionMinutes,
    setMode,
    setMoving,
    setOptionCategory,
    setOptionSearch,
    setOrigin,
    setOriginArea,
    setOriginChoice,
    setOriginCity,
    setOriginCountry,
    setOriginCountryQuery,
    setOriginRegion,
    setParkingPerDay,
    setPlannerStage,
    setPurposes,
    setRequestText,
    setRide,
    setSameOnReturn,
    setSelectedDay,
    setSelectedOptionIds,
    setSelectedPlan,
    setShowDetails,
    setStayStrategy,
    setStops,
    setSubmitted,
    setTab,
    setTransferMode,
    showDetails,
    stayStrategy,
    stops,
    submitted,
    t,
    tab,
    tf,
    timeRemaining,
    toggleDestination,
    toggleJourneyOption,
    toggleLock,
    togglePurpose,
    transferMode,
    useCurrentLocation,
    visibleDestinationRegions,
    visibleOriginCountries,
  } = useTrip();
  return (
    <section className="workspace-view planner-workspace">
      {plannerStage === "input" ? <PlannerInput/> : plannerStage === "results" ? <PlannerResults/> : <PlannerDetail/>}
    </section>
  );
}
